version: "3.4"

services:
  kafka-backend:
    build:
      context: "kafka-backend/"
    image: kafka-backend
    env_file:
      - "./kafka-backend/.env"
    ports:
      - 3000:80

  proyecto:
    build:
      context: "proyecto/"
    image: proyecto
    env_file:
      - "./proyecto/.env"
    ports:
      - 5000:80