version: "3.7"

services:
  kafka-backend:
    build:
      context: "kafka-backend/"
    image: kafka-backend
    ports:
      - 3000:80

  proyecto:
    build:
      context: "proyecto/"
    image: proyecto
    ports:
      - 4200:80